const freelancerProfiles: Array<Mockup.IFreelancerProfile> = [
    {
        id: "1",
        firstName: "Aymen",
        lastName: "Ben Ali",
        profileRating: 4.5,
        role: "Software Engineer",
        profilePicture: "/profilePictures/m1.jpg",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis nobis reiciendis tempore ullam, reprehenderit, officiis natus dignissimos aliquid facere deleniti in a odio ea voluptate harum dolorum. Earum, repellat error. Voluptatum hic, eveniet, odio omnis rerum repudiandae voluptates nobis reprehenderit, totam consectetur rem fuga. Quaerat dolorem aperiam molestiae facilis in. Consequatur magni harum quod vel molestiae nemo impedit sunt alias ad animi eos quisquam mollitia voluptatum recusandae, adipisci et cumque minima nesciunt natus repellat asperiores explicabo fugit voluptate. Quod repellendus voluptatum impedit asperiores unde quisquam adipisci esse tempore facere",
        lastEmploymentString: "il ya 2 jours",
        freelancerDomain: "Product Development",
        freelancerExpertise: "marketing",
        timeEmployment: "Plein temps",
        email: "jeromeBell45@email.com",
        phone: "+44 1245 572 135",
        instagram: "instagram.com/jeromebell",
        twitter: "twitter.com/jeromebell",
        website: "www.jeromebell.com",
        gender: "male",
        birthDate: "March 23, 1995 (26 y.o)",
        birthPlace: "Tunis, Tunisia",
        languages: "English, French",
        address: "4517 Washington Ave. Manchester, Kentucky 39495",
        experience: "4 ans",
        academicCareer: "Bachelors in Engineering",
        skills: ["Project Management", "Copywriting", "English"]
    },
    {
        id: "2",
        firstName: "Fatma",
        lastName: "Trabelsi",
        profileRating: 4.7,
        role: "Data Scientist",
        profilePicture: "/profilePictures/f1.jpg",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis nobis reiciendis tempore ullam, reprehenderit, officiis natus dignissimos aliquid facere deleniti in a odio ea voluptate harum dolorum. Earum, repellat error. Voluptatum hic, eveniet, odio omnis rerum repudiandae voluptates nobis reprehenderit, totam consectetur rem fuga. Quaerat dolorem aperiam molestiae facilis in. Consequatur magni harum quod vel molestiae nemo impedit sunt alias ad animi eos quisquam mollitia voluptatum recusandae, adipisci et cumque minima nesciunt natus repellat asperiores explicabo fugit voluptate. Quod repellendus voluptatum impedit asperiores unde quisquam adipisci esse tempore facere",
        lastEmploymentString: "il y a 1 mois",
        freelancerDomain: "Data Analytics",
        freelancerExpertise: "data visualization",
        timeEmployment: "Temps partiel",
        email: "fatma.trabelsi@email.com",
        phone: "+33 123 456 789",
        instagram: "instagram.com/fatma_trabelsi",
        twitter: "twitter.com/fatma_trabelsi",
        website: "www.fatmatrabelsi.com",
        gender: "female",
        birthDate: "June 15, 1992 (32 y.o)",
        birthPlace: "Paris, France",
        languages: "English, Arabic",
        address: "12 Rue de Paris, Paris, France",
        experience: "6 ans",
        academicCareer: "Masters in Data Science",
        skills: ["Data Analysis", "Python", "SQL"]
    },
    {
        id: "3",
        firstName: "Mohamed",
        lastName: "Hammami",
        profileRating: 4.6,
        role: "Machine Learning Engineer",
        profilePicture: "/profilePictures/m2.jpg",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis nobis reiciendis tempore ullam, reprehenderit, officiis natus dignissimos aliquid facere deleniti in a odio ea voluptate harum dolorum. Earum, repellat error. Voluptatum hic, eveniet, odio omnis rerum repudiandae voluptates nobis reprehenderit, totam consectetur rem fuga. Quaerat dolorem aperiam molestiae facilis in. Consequatur magni harum quod vel molestiae nemo impedit sunt alias ad animi eos quisquam mollitia voluptatum recusandae, adipisci et cumque minima nesciunt natus repellat asperiores explicabo fugit voluptate. Quod repellendus voluptatum impedit asperiores unde quisquam adipisci esse tempore facere",
        lastEmploymentString: "il y a 3 semaines",
        freelancerDomain: "AI & ML",
        freelancerExpertise: "deep learning",
        timeEmployment: "Plein temps",
        email: "mohamed.hammami@email.com",
        phone: "+216 50 123 456",
        instagram: "instagram.com/mohamed_hammami",
        twitter: "twitter.com/mohamed_hammami",
        website: "www.mohamedhammami.com",
        gender: "male",
        birthDate: "October 5, 1989 (34 y.o)",
        birthPlace: "Tunis, Tunisia",
        languages: "English, Arabic",
        address: "4 Rue de Tunis, Tunis, Tunisia",
        experience: "8 ans",
        academicCareer: "PhD in Machine Learning",
        skills: ["TensorFlow", "Keras", "Neural Networks"]
    },
    {
        id: "4",
        firstName: "Salma",
        lastName: "Khaled",
        profileRating: 4.8,
        role: "AI Researcher",
        profilePicture: "/profilePictures/f2.jpg",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis nobis reiciendis tempore ullam, reprehenderit, officiis natus dignissimos aliquid facere deleniti in a odio ea voluptate harum dolorum. Earum, repellat error. Voluptatum hic, eveniet, odio omnis rerum repudiandae voluptates nobis reprehenderit, totam consectetur rem fuga. Quaerat dolorem aperiam molestiae facilis in. Consequatur magni harum quod vel molestiae nemo impedit sunt alias ad animi eos quisquam mollitia voluptatum recusandae, adipisci et cumque minima nesciunt natus repellat asperiores explicabo fugit voluptate. Quod repellendus voluptatum impedit asperiores unde quisquam adipisci esse tempore facere",
        lastEmploymentString: "il y a 2 semaines",
        freelancerDomain: "AI Research",
        freelancerExpertise: "natural language processing",
        timeEmployment: "Plein temps",
        email: "salma.khaled@email.com",
        phone: "+20 123 456 789",
        instagram: "instagram.com/salma_khaled",
        twitter: "twitter.com/salma_khaled",
        website: "www.salmakhaled.com",
        gender: "female",
        birthDate: "April 22, 1987 (37 y.o)",
        birthPlace: "Marseille, France",
        languages: "English, Arabic",
        address: "24 Boulevard Longchamp, Marseille, France",
        experience: "10 ans",
        academicCareer: "Masters in Artificial Intelligence",
        skills: ["NLP", "Python", "Research"]
    },
    {
        id: "5",
        firstName: "Nour",
        lastName: "Maaloul",
        profileRating: 4.4,
        role: "DevOps Engineer",
        profilePicture: "/profilePictures/f3.jpg",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis nobis reiciendis tempore ullam, reprehenderit, officiis natus dignissimos aliquid facere deleniti in a odio ea voluptate harum dolorum. Earum, repellat error. Voluptatum hic, eveniet, odio omnis rerum repudiandae voluptates nobis reprehenderit, totam consectetur rem fuga. Quaerat dolorem aperiam molestiae facilis in. Consequatur magni harum quod vel molestiae nemo impedit sunt alias ad animi eos quisquam mollitia voluptatum recusandae, adipisci et cumque minima nesciunt natus repellat asperiores explicabo fugit voluptate. Quod repellendus voluptatum impedit asperiores unde quisquam adipisci esse tempore facere",
        lastEmploymentString: "il y a 1 mois",
        freelancerDomain: "DevOps",
        freelancerExpertise: "cloud infrastructure",
        timeEmployment: "Plein temps",
        email: "nour.maaloul@email.com",
        phone: "+961 71 234 567",
        instagram: "instagram.com/nour_maaloul",
        twitter: "twitter.com/nour_maaloul",
        website: "www.nourmaaloul.com",
        gender: "female",
        birthDate: "August 12, 1990 (33 y.o)",
        birthPlace: "Tunis, Tunisia",
        languages: "English, Arabic",
        address: "8 Rue de Beirut, Beirut, Lebanon",
        experience: "5 ans",
        academicCareer: "Bachelors in Computer Science",
        skills: ["AWS", "Docker", "CI/CD"]
    },
    {
        id: "6",
        firstName: "Rania",
        lastName: "Bouzid",
        profileRating: 4.3,
        role: "Frontend Developer",
        profilePicture: "/profilePictures/f4.jpg",
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aut quis nobis reiciendis tempore ullam, reprehenderit, officiis natus dignissimos aliquid facere deleniti in a odio ea voluptate harum dolorum. Earum, repellat error. Voluptatum hic, eveniet, odio omnis rerum repudiandae voluptates nobis reprehenderit, totam consectetur rem fuga. Quaerat dolorem aperiam molestiae facilis in. Consequatur magni harum quod vel molestiae nemo impedit sunt alias ad animi eos quisquam mollitia voluptatum recusandae, adipisci et cumque minima nesciunt natus repellat asperiores explicabo fugit voluptate. Quod repellendus voluptatum impedit asperiores unde quisquam adipisci esse tempore facere",
        lastEmploymentString: "il y a 2 jours",
        freelancerDomain: "Web Development",
        freelancerExpertise: "React.js",
        timeEmployment: "Plein temps",
        email: "rania.bouzid@email.com",
        phone: "+216 70 123 456",
        instagram: "instagram.com/rania_bouzid",
        twitter: "twitter.com/rania_bouzid",
        website: "www.raniabouzid.com",
        gender: "female",
        birthDate: "January 29, 1994 (30 y.o)",
        birthPlace: "Lille, France",
        languages: "English, French",
        address: "10 Rue de Lille, Lille, France",
        experience: "3 ans",
        academicCareer: "Bachelors in Web Development",
        skills: ["React.js", "CSS", "JavaScript"]
    }
];


export default freelancerProfiles;